[pytest]
norecursedirs =
    lambda/get_env_data/annotated_types
    lambda/get_env_data/boto3
    lambda/get_env_data/botocore
    lambda/get_env_data/certifi
    lambda/get_env_data/charset_normalizer
    lambda/get_env_data/idna
    lambda/get_env_data/jmespath
    lambda/get_env_data/pydantic
    lambda/get_env_data/pydantic_core
    lambda/get_env_data/requests
    lambda/get_env_data/s3transfer
    lambda/get_env_data/typing_inspection
    lambda/get_env_data/urllib3
    lambda/get_env_data/bin
    lambda/get_env_data/clients
    lambda/get_env_data/services
    .git
    __pycache__
    node_modules
    .venv
